function SpawnRegions()
	return {
		{ name = "adelaide", file = "media/maps/adelaide/spawnpoints.lua" },
		{ name = "ayrton", file = "media/maps/ayrton/spawnpoints.lua" },
		{ name = "bdizzle", file = "media/maps/bdizzle/spawnpoints.lua" },
		{ name = "ben", file = "media/maps/ben/spawnpoints.lua" },
		{ name = "bonnefoy", file = "media/maps/bonnefoy/spawnpoints.lua" },
		{ name = "cherbourg", file = "media/maps/cherbourg/spawnpoints.lua" },
		{ name = "claire", file = "media/maps/claire/spawnpoints.lua" },
		{ name = "daniel", file = "media/maps/daniel/spawnpoints.lua" },
		{ name = "darin", file = "media/maps/darin/spawnpoints.lua" },
		{ name = "david", file = "media/maps/david/spawnpoints.lua" },
		{ name = "DialloBoubakar", file = "media/maps/DialloBoubakar/spawnpoints.lua" },
		{ name = "didier", file = "media/maps/didier/spawnpoints.lua" },
		{ name = "iltud", file = "media/maps/iltud/spawnpoints.lua" },
		{ name = "johan", file = "media/maps/johan/spawnpoints.lua" },
		{ name = "julien", file = "media/maps/julien/spawnpoints.lua" },
		{ name = "kate", file = "media/maps/kate/spawnpoints.lua" },
		{ name = "legumanigo", file = "media/maps/legumanigo/spawnpoints.lua" },
		{ name = "perle", file = "media/maps/perle/spawnpoints.lua" },
		{ name = "ray", file = "media/maps/ray/spawnpoints.lua" },
		{ name = "romain", file = "media/maps/romain/spawnpoints.lua" },
		{ name = "simeon", file = "media/maps/simeon/spawnpoints.lua" },
		{ name = "Yemmlie", file = "media/maps/Yemmlie/spawnpoints.lua" },
		{ name = "cherbourg_map", file = "media/maps/cherbourg_map/spawnpoints.lua" },
	}
end
