function SpawnRegions()
	return {
		{ name = "Muldraugh, KY",                     file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Riverside, KY",                     file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY",                      file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY",                    file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Addams Mansion",                    file = "media/maps/Addams Mansion/spawnpoints.lua" },
		{ name = "Ashenwood",                         file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "BBL",                               file = "media/maps/BBL/spawnpoints.lua" },
		{ name = "BedfordFalls",                      file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "Blackwood",                         file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "Breakpoint",                        file = "media/maps/Breakpoint/spawnpoints.lua" },
		{ name = "DayOfTheDead",                      file = "media/maps/DayOfTheDead/spawnpoints.lua" },
		{ name = "Canvasback",                        file = "media/maps/Canvasback/spawnpoints.lua" },
		{ name = "EastTownofRiverside",               file = "media/maps/EastTownofRiverside/spawnpoints.lua" },
		{ name = "Cedar Hill",                        file = "media/maps/Cedar Hill/spawnpoints.lua" },
		{ name = "chernaville",                       file = "media/maps/chernaville/spawnpoints.lua" },
		{ name = "Chestown",                          file = "media/maps/Chestown/spawnpoints.lua" },
		{ name = "Chinatown",                         file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "Chinatown_EX",                      file = "media/maps/Chinatown_EX/spawnpoints.lua" },
		{ name = "CigaroHouse",                       file = "media/maps/CigaroHouse/spawnpoints.lua" },
		{ name = "C_Madriguera",                      file = "media/maps/C_Madriguera/spawnpoints.lua" },
		{ name = "CONRTF",                            file = "media/maps/CONRTF/spawnpoints.lua" },
		{ name = "CorOTRroad",                        file = "media/maps/CorOTRroad/spawnpoints.lua" },
		{ name = "coryerdon",                         file = "media/maps/coryerdon/spawnpoints.lua" },
		{ name = "Cryo Compound",                     file = "media/maps/Cryo Compound/spawnpoints.lua" },
		{ name = "betsysfarm",                        file = "media/maps/betsysfarm/spawnpoints.lua" },
		{ name = "DoubleDeckerBus",                   file = "media/maps/DoubleDeckerBus/spawnpoints.lua" },
		{ name = "EdsAutoSalvage",                    file = "media/maps/EdsAutoSalvage/spawnpoints.lua" },
		{ name = "Eerie A",                           file = "media/maps/Eerie A/spawnpoints.lua" },
		{ name = "Eerie B",                           file = "media/maps/Eerie B/spawnpoints.lua" },
		{ name = "Eerie C",                           file = "media/maps/Eerie C/spawnpoints.lua" },
		{ name = "Eerie Country",                     file = "media/maps/Eerie Country/spawnpoints.lua" },
		{ name = "Eerie D",                           file = "media/maps/Eerie D/spawnpoints.lua" },
		{ name = "elliotpondec",                      file = "media/maps/elliotpondec/spawnpoints.lua" },
		{ name = "Elysium_Island",                    file = "media/maps/Elysium_Island/spawnpoints.lua" },
		{ name = "EVAC_Muldraugh",                    file = "media/maps/EVAC_Muldraugh/spawnpoints.lua" },
		{ name = "Farm house",                        file = "media/maps/Farm house/spawnpoints.lua" },
		{ name = "Lone",                              file = "media/maps/Lone/spawnpoints.lua" },
		{ name = "Fort Knox, KY by Woldren",          file = "media/maps/Fort Knox, KY by Woldren/spawnpoints.lua" },
		{ name = "Fort Rock Ridge",                   file = "media/maps/Fort Rock Ridge/spawnpoints.lua" },
		{ name = "Fort_Boonesborough",                file = "media/maps/Fort_Boonesborough/spawnpoints.lua" },
		{ name = "Fort Knox linked to Eerie Country", file = "media/maps/Fort Knox linked to Eerie Country/spawnpoints.lua" },
		{ name = "Near Fort Knox",                    file = "media/maps/Near Fort Knox/spawnpoints.lua" },
		{ name = "To Bedford Falls",                  file = "media/maps/To Bedford Falls/spawnpoints.lua" },
		{ name = "To Eerie Country",                  file = "media/maps/To Eerie Country/spawnpoints.lua" },
		{ name = "From Bedford Falls to Fort Knox",   file = "media/maps/From Bedford Falls to Fort Knox/spawnpoints.lua" },
		{ name = "FortRedstone",                      file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Grapeseed",                         file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "Greenleaf",                         file = "media/maps/Greenleaf/spawnpoints.lua" },
		{ name = "Greenport",                         file = "media/maps/Greenport/spawnpoints.lua" },
		{ name = "Heavens Hill",                      file = "media/maps/Heavens Hill/spawnpoints.lua" },
		{ name = "Hilltop",                           file = "media/maps/Hilltop/spawnpoints.lua" },
		{ name = "Hopewell, KY",                      file = "media/maps/Hopewell, KY/spawnpoints.lua" },
		{ name = "HouseLuisMatrioshka",               file = "media/maps/HouseLuisMatrioshka/spawnpoints.lua" },
		{ name = "Hunter'sBase_map",                  file = "media/maps/Hunter'sBase_map/spawnpoints.lua" },
	}
end
